import React, { Component } from "react";
import { Stickynav, ProductJumbo, ProductText } from "arccorp-vars";

class App extends Component {
  constructor() {
    super();
  }

  render() {
    return (
      <div className="advanced-data-analytics-page">
        <Stickynav
          title="Advanced Data Analytics"
          links={[
            { title: "Overview", url: "#overview" },
            { title: "Solutions", url: "#solutions" },
          ]}
        ></Stickynav>
        <ProductJumbo
          backgroundImage="https://www2.arccorp.com/globalassets/products--participation/advanced-data-analytics/ada-jumbo.png"
          title={
            <>
              Advanced data analytics <br />
              using Artificial Intelligence
            </>
          }
          width="100%"
          subtitle={
            <>
              Solving the most complex business challenges using{" "}
              <span>
                ARC's machine learning techniques and technology provides
                innovative analytical travel-related data.
              </span>
            </>
          }
        ></ProductJumbo>
        <ProductText
          id="overview"
          eyebrow="Overview"
          titleClass=""
          title={
            <>
              A Better Way to Make <br />
              Business Decisions{" "}
            </>
          }
          subtitle="ARC's advanced analytic capabilities combine AI with years of industry experience to create groundbreaking travel data. Leveraging Amazon's SageMaker technology, ARC provides next-generation solutions for airline Cabin Class Mapping, Total Air Market estimates, Quality Service Index and Trip Classification."
        />
        <ProductText
          id="solutions"
          className="ada-solutions"
          eyebrow="Solutions"
          backgroundImage="https://www2.arccorp.com/globalassets/products--participation/advanced-data-analytics/ada-solutions-bg.png"
          title={<>ARC Total Air Market</>}
          subtitle={
            <>
              Estimated datasets enable customers to understand total global air
              market size, carrier market shares, traffic distribution, demand
              growth and fare patterns. The information provided by ARC’s Total
              Air Market (TAM) data can be used for{" "}
              <span>strategic planning</span> and{" "}
              <span className="white">operational management</span> in specific
              markets.
            </>
          }
          body={
            <>
              <div className="row" style={{ marginBottom: "80px" }}>
                <div className="col-lg-6">
                  <div className="ada-solutions-card card-1">
                    <div>
                      Total market size at the{" "}
                      <span className="white">
                        flight
                        <br /> coupon level
                      </span>{" "}
                      is provided with
                      <br /> <span>actual tickets</span> and estimates
                      <br /> of extra traffic.
                    </div>
                  </div>
                </div>
                <div className="col-lg-6">
                  <div className="ada-solutions-card">
                    <div>
                      Datasets with sales, refund and exchange information are{" "}
                      <span>updated weekly</span>. Estimates are generated by
                      including total traffic statistics from nearly{" "}
                      <span className="white">2000 airports</span>
                      and load factors from more than{" "}
                      <span className="white">400 airlines</span>.
                    </div>
                  </div>
                </div>
              </div>
              <div className="row">
                <div className="col-lg">
                  <div className="ada-solutions-icon">
                    <img
                      src="https://www2.arccorp.com/globalassets/products--participation/advanced-data-analytics/speed.png"
                      alt="Speed"
                    />
                    <br />
                    <div className="ada-solutions-icon-title">Speed</div>
                    <div className="ada-solutions-icon-copy">
                      Updates are
                      <br /> refreshed with a<br /> minimal lag time.
                    </div>
                  </div>
                </div>
                <div className="col-lg">
                  <div className="ada-solutions-icon">
                    <img
                      src="https://www2.arccorp.com/globalassets/products--participation/advanced-data-analytics/segmentation.png"
                      alt="Segmentation"
                    />
                    <br />
                    <div className="ada-solutions-icon-title">Segmentation</div>
                    <div className="ada-solutions-icon-copy">
                      Understand traveler
                      <br />
                      profiles and trip
                      <br />
                      characteristics.
                    </div>
                  </div>
                </div>
                <div className="col-lg">
                  <div className="ada-solutions-icon">
                    <img
                      src="https://www2.arccorp.com/globalassets/products--participation/advanced-data-analytics/thorough.png"
                      alt="Thorough"
                    />
                    <br />
                    <div className="ada-solutions-icon-title">Thorough</div>
                    <div className="ada-solutions-icon-copy">
                      Thorough analysis
                      <br />
                      down to airport terminal <br />
                      and flight level.
                    </div>
                  </div>
                </div>
                <div className="col-lg">
                  <div className="ada-solutions-icon">
                    <img
                      src="https://www2.arccorp.com/globalassets/products--participation/advanced-data-analytics/updates.png"
                      alt="Updates"
                    />
                    <br />
                    <div className="ada-solutions-icon-title">Updates</div>
                    <div className="ada-solutions-icon-copy">
                      Regular recalibrations
                      <br />
                      and adjustments
                      <br />
                      of TAM.
                    </div>
                  </div>
                </div>
                <div className="col-lg">
                  <div className="ada-solutions-icon">
                    <img
                      src="https://www2.arccorp.com/globalassets/products--participation/advanced-data-analytics/quality.png"
                      alt="Quality"
                    />
                    <br />
                    <div className="ada-solutions-icon-title">Quality</div>
                    <div className="ada-solutions-icon-copy">
                      Extensive quality
                      <br />
                      control and validation
                      <br />
                      checks.
                    </div>
                  </div>
                </div>
              </div>
            </>
          }
        />
      </div>
    );
  }
}

export default App;
